import '../models/cycle_log.dart';
import '../models/cycle_settings.dart';
import '../models/symptom_pattern.dart';

/// A fully structured export report.
/// The UI layer is responsible for rendering this as PDF or sharing it;
/// this class only concerns itself with the data.
class ExportReport {
  final DateTime generatedAt;
  final String userName;
  final DateRange dateRange;
  final List<CycleSummaryEntry> cycleSummaries;
  final SymptomFrequencySummary symptomSummary;
  final List<DailyEntry> dailyEntries;
  final List<String> medicationsTracked;
  final List<String> supplementsTracked;
  final List<MoodTrendEntry> moodTrend;
  final List<String> notablePatterns;
  final List<ClinicalNote> clinicalNotes;
  // Only populated if user has enabled journalInExports
  final List<JournalExcerpt>? journalExcerpts;
  final String disclaimer;

  const ExportReport({
    required this.generatedAt,
    required this.userName,
    required this.dateRange,
    required this.cycleSummaries,
    required this.symptomSummary,
    required this.dailyEntries,
    required this.medicationsTracked,
    required this.supplementsTracked,
    required this.moodTrend,
    required this.notablePatterns,
    required this.clinicalNotes,
    this.journalExcerpts,
    required this.disclaimer,
  });
}

class DateRange {
  final DateTime start;
  final DateTime end;
  const DateRange({required this.start, required this.end});
}

class CycleSummaryEntry {
  final int cycleNumber;
  final DateTime periodStart;
  final DateTime? periodEnd;
  final int? cycleLength;
  final int? periodLength;
  final String peakSymptom;
  final int avgPainLevel;
  const CycleSummaryEntry({
    required this.cycleNumber,
    required this.periodStart,
    this.periodEnd,
    this.cycleLength,
    this.periodLength,
    required this.peakSymptom,
    required this.avgPainLevel,
  });
}

class SymptomFrequencySummary {
  // symptom name → number of days logged in the date range
  final Map<String, int> physicalFrequency;
  final Map<String, int> emotionalFrequency;
  final Map<String, int> pmddFrequency;
  final int totalDaysLogged;
  final double avgPain;
  final double avgEnergy;
  final double avgSleep;
  const SymptomFrequencySummary({
    required this.physicalFrequency,
    required this.emotionalFrequency,
    required this.pmddFrequency,
    required this.totalDaysLogged,
    required this.avgPain,
    required this.avgEnergy,
    required this.avgSleep,
  });
}

class DailyEntry {
  final String date;
  final String flow;
  final int painLevel;
  final int energy;
  final int sleep;
  final List<String> symptoms;
  final List<String> medications;
  final List<String> supplements;
  final String? notes;
  const DailyEntry({
    required this.date,
    required this.flow,
    required this.painLevel,
    required this.energy,
    required this.sleep,
    required this.symptoms,
    required this.medications,
    required this.supplements,
    this.notes,
  });
}

class MoodTrendEntry {
  final String weekLabel;
  final double avgMoodScore;
  final List<String> dominantSymptoms;
  const MoodTrendEntry({
    required this.weekLabel,
    required this.avgMoodScore,
    required this.dominantSymptoms,
  });
}

class ClinicalNote {
  final String category;
  final String content;
  const ClinicalNote({required this.category, required this.content});
}

class JournalExcerpt {
  final String date;
  final String text;
  const JournalExcerpt({required this.date, required this.text});
}

class ExportService {
  static const String _disclaimer =
      'This report was generated by SOL Cycle, a wellness and body-literacy app. '
      'It reflects personal logs entered by the user and is intended to support '
      'conversation with a healthcare provider. It does not constitute a medical record, '
      'diagnosis, or clinical assessment. Please share with your provider as supplementary '
      'information only.';

  /// Generates a full structured report from all logs.
  /// Pass [dateRange] to limit scope; pass null for all-time.
  static ExportReport generate({
    required Map<String, CycleLog> logs,
    required CycleSettings settings,
    SymptomPattern? pattern,
    DateRange? dateRange,
    bool includeJournal = false,
  }) {
    final allDates = logs.keys.toList()..sort();
    if (allDates.isEmpty) {
      return _emptyReport(settings, dateRange);
    }

    final rangeStart = dateRange?.start ?? DateTime.parse(allDates.first);
    final rangeEnd = dateRange?.end ?? DateTime.parse(allDates.last);

    final filteredLogs = logs.entries
        .where((e) {
          final d = DateTime.parse(e.key);
          return !d.isBefore(rangeStart) && !d.isAfter(rangeEnd);
        })
        .map((e) => e.value)
        .toList()
      ..sort((a, b) => a.date.compareTo(b.date));

    final cycleSummaries = _buildCycleSummaries(filteredLogs, settings);
    final symptomSummary = _buildSymptomSummary(filteredLogs);
    final dailyEntries = _buildDailyEntries(filteredLogs, settings);
    final moodTrend = _buildMoodTrend(filteredLogs);
    final medications = _uniqueList(filteredLogs.expand((l) => l.medications));
    final supplements = _uniqueList(filteredLogs.expand((l) => l.supplements));
    final notablePatterns = _buildNotablePatterns(filteredLogs, pattern, settings);
    final clinicalNotes = _buildClinicalNotes(filteredLogs, symptomSummary, settings);

    List<JournalExcerpt>? journalExcerpts;
    if (includeJournal && settings.journalInExports) {
      journalExcerpts = filteredLogs
          .where((l) => l.journalEntry != null && l.journalEntry!.isNotEmpty)
          .map((l) => JournalExcerpt(date: l.date, text: l.journalEntry!))
          .toList();
    }

    return ExportReport(
      generatedAt: DateTime.now(),
      userName: settings.name.isNotEmpty ? settings.name : 'SOL Cycle User',
      dateRange: DateRange(start: rangeStart, end: rangeEnd),
      cycleSummaries: cycleSummaries,
      symptomSummary: symptomSummary,
      dailyEntries: dailyEntries,
      medicationsTracked: medications,
      supplementsTracked: supplements,
      moodTrend: moodTrend,
      notablePatterns: notablePatterns,
      clinicalNotes: clinicalNotes,
      journalExcerpts: journalExcerpts,
      disclaimer: _disclaimer,
    );
  }

  /// Generates a compact clinician-focused summary (fewer fields, cleaner layout).
  static Map<String, dynamic> clinicianSummary({
    required ExportReport report,
    required CycleSettings settings,
  }) {
    return {
      'generatedAt': report.generatedAt.toIso8601String(),
      'userName': report.userName,
      'reportPeriod': {
        'from': _fmtDate(report.dateRange.start),
        'to': _fmtDate(report.dateRange.end),
      },
      'cycleSummary': {
        'cyclesLogged': report.cycleSummaries.length,
        'averageCycleLength': settings.averageCycleLength,
        'cycles': report.cycleSummaries.map((c) => {
          'periodStart': _fmtDate(c.periodStart),
          'cycleLength': c.cycleLength,
          'periodLength': c.periodLength,
          'avgPainLevel': c.avgPainLevel,
          'peakSymptom': c.peakSymptom,
        }).toList(),
      },
      'topPhysicalSymptoms': _topN(report.symptomSummary.physicalFrequency, 5),
      'topEmotionalSymptoms': _topN(report.symptomSummary.emotionalFrequency, 5),
      'topPmddSymptoms': report.symptomSummary.pmddFrequency.isNotEmpty
          ? _topN(report.symptomSummary.pmddFrequency, 5)
          : null,
      'averages': {
        'painLevel': report.symptomSummary.avgPain.toStringAsFixed(1),
        'energyLevel': report.symptomSummary.avgEnergy.toStringAsFixed(1),
        'sleepHours': report.symptomSummary.avgSleep.toStringAsFixed(1),
      },
      'medicationsTracked': report.medicationsTracked,
      'supplementsTracked': report.supplementsTracked,
      'notablePatterns': report.notablePatterns,
      'clinicalNotes': report.clinicalNotes.map((n) => {
        'category': n.category,
        'note': n.content,
      }).toList(),
      'disclaimer': report.disclaimer,
    };
  }

  // ─── Builders ──────────────────────────────────────────────────────────────

  static List<CycleSummaryEntry> _buildCycleSummaries(
      List<CycleLog> logs, CycleSettings settings) {
    final entries = <CycleSummaryEntry>[];
    DateTime? currentStart;
    DateTime? lastBleedDate;
    Map<String, int> symCounts = {};
    List<int> painLevels = [];
    int cycleNum = 1;
    DateTime? prevBleedStart;

    for (final log in logs) {
      final date = DateTime.parse(log.date);
      final isBleed = log.flow != 'none' && log.flow != 'spotting';

      if (isBleed && (lastBleedDate == null || date.difference(lastBleedDate).inDays > 1)) {
        if (currentStart != null) {
          entries.add(CycleSummaryEntry(
            cycleNumber: cycleNum++,
            periodStart: currentStart,
            periodEnd: lastBleedDate,
            cycleLength: prevBleedStart != null
                ? currentStart.difference(prevBleedStart).inDays
                : null,
            periodLength: lastBleedDate != null
                ? lastBleedDate.difference(currentStart).inDays + 1
                : null,
            peakSymptom: _peakSymptom(symCounts),
            avgPainLevel: painLevels.isEmpty
                ? 0
                : (painLevels.reduce((a, b) => a + b) / painLevels.length).round(),
          ));
          symCounts = {};
          painLevels = [];
          prevBleedStart = currentStart;
        }
        currentStart = date;
      }

      if (currentStart != null) {
        if (isBleed) lastBleedDate = date;
        for (final s in log.allSymptoms) {
          symCounts[s] = (symCounts[s] ?? 0) + 1;
        }
        if (log.painLevel > 0) painLevels.add(log.painLevel);
      }
    }

    if (currentStart != null && symCounts.isNotEmpty) {
      entries.add(CycleSummaryEntry(
        cycleNumber: cycleNum,
        periodStart: currentStart,
        periodEnd: lastBleedDate,
        cycleLength: null,
        periodLength: lastBleedDate != null
            ? lastBleedDate.difference(currentStart).inDays + 1
            : null,
        peakSymptom: _peakSymptom(symCounts),
        avgPainLevel: painLevels.isEmpty
            ? 0
            : (painLevels.reduce((a, b) => a + b) / painLevels.length).round(),
      ));
    }

    return entries;
  }

  static SymptomFrequencySummary _buildSymptomSummary(List<CycleLog> logs) {
    final physical = <String, int>{};
    final emotional = <String, int>{};
    final pmdd = <String, int>{};
    double totalPain = 0;
    double totalEnergy = 0;
    double totalSleep = 0;

    for (final log in logs) {
      for (final s in log.physicalSymptoms) {
        physical[s] = (physical[s] ?? 0) + 1;
      }
      for (final s in log.emotionalSymptoms) {
        emotional[s] = (emotional[s] ?? 0) + 1;
      }
      for (final s in log.pmddSymptoms) {
        pmdd[s] = (pmdd[s] ?? 0) + 1;
      }
      totalPain += log.painLevel;
      totalEnergy += log.energy;
      totalSleep += log.sleep;
    }

    final count = logs.length;
    return SymptomFrequencySummary(
      physicalFrequency: physical,
      emotionalFrequency: emotional,
      pmddFrequency: pmdd,
      totalDaysLogged: count,
      avgPain: count > 0 ? totalPain / count : 0,
      avgEnergy: count > 0 ? totalEnergy / count : 0,
      avgSleep: count > 0 ? totalSleep / count : 0,
    );
  }

  static List<DailyEntry> _buildDailyEntries(
      List<CycleLog> logs, CycleSettings settings) {
    return logs.map((log) {
      return DailyEntry(
        date: log.date,
        flow: log.flow,
        painLevel: log.painLevel,
        energy: log.energy,
        sleep: log.sleep,
        symptoms: log.allSymptoms,
        medications: log.medications,
        supplements: log.supplements,
        notes: log.notes.isNotEmpty ? log.notes : null,
      );
    }).toList();
  }

  static List<MoodTrendEntry> _buildMoodTrend(List<CycleLog> logs) {
    if (logs.isEmpty) return [];
    final weeks = <String, List<CycleLog>>{};
    for (final log in logs) {
      final d = DateTime.parse(log.date);
      final weekStart = d.subtract(Duration(days: d.weekday - 1));
      final key = _fmtDate(weekStart);
      weeks.putIfAbsent(key, () => []).add(log);
    }

    return weeks.entries.map((entry) {
      final weekLogs = entry.value;
      final moodScores = weekLogs
          .map((l) => _moodScore(l.emotionalSymptoms + l.pmddSymptoms))
          .toList();
      final avg = moodScores.reduce((a, b) => a + b) / moodScores.length;
      final symCounts = <String, int>{};
      for (final log in weekLogs) {
        for (final s in log.emotionalSymptoms + log.pmddSymptoms) {
          symCounts[s] = (symCounts[s] ?? 0) + 1;
        }
      }
      final dominant = symCounts.entries.toList()..sort((a, b) => b.value.compareTo(a.value));
      return MoodTrendEntry(
        weekLabel: 'Week of ${entry.key}',
        avgMoodScore: avg,
        dominantSymptoms: dominant.take(3).map((e) => e.key).toList(),
      );
    }).toList();
  }

  static List<String> _buildNotablePatterns(
      List<CycleLog> logs, SymptomPattern? pattern, CycleSettings settings) {
    final notes = <String>[];
    if (pattern == null) return notes;

    if (pattern.highPainRelativeDays.isNotEmpty) {
      notes.add('Pain tends to cluster around days '
          '${pattern.highPainRelativeDays.join(', ')} relative to the start of bleeding.');
    }
    if (pattern.highMoodSymptomRelativeDays.isNotEmpty) {
      notes.add('Emotional and mood symptoms are most frequent in the days before bleeding '
          '(approximately days ${pattern.highMoodSymptomRelativeDays.map((d) => d >= 0 ? '+$d' : '$d').join(', ')}).');
    }
    if (pattern.cycleVariability > 5) {
      notes.add('Cycle length has been variable (standard deviation: '
          '${pattern.cycleVariability.toStringAsFixed(1)} days). '
          'This may be worth discussing with a provider.');
    }

    final avgPainByPhase = pattern.avgPainByPhase;
    if (avgPainByPhase.isNotEmpty) {
      final highPainPhase = avgPainByPhase.entries
          .reduce((a, b) => a.value > b.value ? a : b);
      if (highPainPhase.value >= 5) {
        notes.add('Average pain is highest during the ${highPainPhase.key} phase '
            '(avg: ${highPainPhase.value.toStringAsFixed(1)}/10).');
      }
    }

    return notes;
  }

  static List<ClinicalNote> _buildClinicalNotes(
      List<CycleLog> logs, SymptomFrequencySummary summary, CycleSettings settings) {
    final notes = <ClinicalNote>[];

    if (summary.avgPain >= 6) {
      notes.add(const ClinicalNote(
        category: 'Pain',
        content: 'Average logged pain level is 6 or above. Severe or frequent pain with '
            'periods may warrant further evaluation (e.g., endometriosis, adenomyosis, '
            'fibroids, or dysmenorrhea).',
      ));
    }

    final heavyDays = logs.where((l) => l.flow == 'heavy').length;
    if (heavyDays >= 3) {
      notes.add(ClinicalNote(
        category: 'Bleeding',
        content: 'Heavy flow was logged on $heavyDays occasions during this period. '
            'Frequently heavy periods may warrant evaluation for underlying causes '
            'including fibroids, adenomyosis, or bleeding disorders.',
      ));
    }

    final pmddFreq = summary.pmddFrequency;
    if (pmddFreq.isNotEmpty) {
      final topPmdd = pmddFreq.entries.toList()
        ..sort((a, b) => b.value.compareTo(a.value));
      final top3 = topPmdd.take(3).map((e) => '${e.key} (${e.value} days)').join(', ');
      notes.add(ClinicalNote(
        category: 'Premenstrual symptoms',
        content: 'PMDD-mode symptoms logged: $top3. '
            'If these symptoms are severe or cyclical, they may be consistent with '
            'PMDD or a related condition and warrant clinical evaluation.',
      ));
    }

    if (settings.endoMode) {
      notes.add(const ClinicalNote(
        category: 'Endometriosis mode',
        content: 'User has endometriosis mode enabled. Logged symptoms may reflect '
            'pain patterns or quality-of-life impact consistent with endometriosis or '
            'similar pelvic conditions.',
      ));
    }

    return notes;
  }

  // ─── Utilities ─────────────────────────────────────────────────────────────

  static String _peakSymptom(Map<String, int> counts) {
    if (counts.isEmpty) return 'none logged';
    return counts.entries.reduce((a, b) => a.value > b.value ? a : b).key;
  }

  static double _moodScore(List<String> symptoms) {
    // Inverted score: more negative mood symptoms = lower score
    const negativeSymptoms = {
      'low mood', 'depression', 'severe depression', 'hopelessness',
      'rage', 'irritability', 'severe irritability', 'anxiety',
      'mood swings', 'tearfulness', 'brain fog',
    };
    final negCount =
        symptoms.where((s) => negativeSymptoms.contains(s.toLowerCase())).length;
    return (10 - negCount).clamp(0, 10).toDouble();
  }

  static List<String> _uniqueList(Iterable<String> items) {
    return items.toSet().toList()..sort();
  }

  static List<Map<String, dynamic>> _topN(Map<String, int> freq, int n) {
    final sorted = freq.entries.toList()..sort((a, b) => b.value.compareTo(a.value));
    return sorted.take(n).map((e) => {'symptom': e.key, 'daysLogged': e.value}).toList();
  }

  static String _fmtDate(DateTime d) =>
      '${d.year}-${d.month.toString().padLeft(2, '0')}-${d.day.toString().padLeft(2, '0')}';

  static ExportReport _emptyReport(CycleSettings settings, DateRange? range) {
    final now = DateTime.now();
    return ExportReport(
      generatedAt: now,
      userName: settings.name.isNotEmpty ? settings.name : 'SOL Cycle User',
      dateRange: range ?? DateRange(start: now, end: now),
      cycleSummaries: const [],
      symptomSummary: const SymptomFrequencySummary(
        physicalFrequency: {},
        emotionalFrequency: {},
        pmddFrequency: {},
        totalDaysLogged: 0,
        avgPain: 0,
        avgEnergy: 0,
        avgSleep: 0,
      ),
      dailyEntries: const [],
      medicationsTracked: const [],
      supplementsTracked: const [],
      moodTrend: const [],
      notablePatterns: const [],
      clinicalNotes: const [],
      disclaimer: _disclaimer,
    );
  }
}
